# Generated by Django 5.0.1 on 2024-01-22 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=50)),
                ('tournament_rules', models.TextField()),
                ('participants', models.IntegerField()),
                ('squad', models.CharField(choices=[('Solo', 'Solo'), ('Duo', 'Duo'), ('Squad', 'Squad')], max_length=30)),
                ('weapon', models.CharField(choices=[('M416', 'M416'), ('M24', 'M24')], max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finished', models.BooleanField(blank=True, null=True)),
                ('available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('round_name', models.CharField(max_length=50)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('match_name', models.CharField(max_length=50)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player2', to=settings.AUTH_USER_MODEL)),
                ('round_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approved', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.tournament')),
            ],
        ),
    ]
