# Generated by Django 5.0.1 on 2024-01-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
