# Generated by Django 5.0.1 on 2024-01-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tournament_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='weapon',
            field=models.CharField(choices=[('M416', 'M416'), ('M24', 'M24')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
