# Generated by Django 5.0.1 on 2024-01-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
