# Generated by Django 5.0.1 on 2024-01-23 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_round_current_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='first_match',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='second_match',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='third_match',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='total',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='forround',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.round'),
        ),
    ]
