# Generated by Django 5.0.1 on 2024-01-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_match_first_match_match_second_match_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
