# Generated by Django 5.0.1 on 2024-01-25 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_round_options_round_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='finished',
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Upcoming', 'Upcoming'), ('Ongoing', 'Ongoing'), ('Finished', 'Finished')], default=1, max_length=35),
            preserve_default=False,
        ),
    ]
