# Generated by Django 5.0.1 on 2024-01-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_tournament_finished_tournament_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
