# Generated by Django 5.0.1 on 2024-01-25 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_tournament_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='status',
            new_name='finished',
        ),
    ]
