# Generated by Django 5.0.1 on 2024-01-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_participant_participant_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_open',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
