# Generated by Django 5.0.1 on 2024-01-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_request_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
