# Generated by Django 5.0.1 on 2024-01-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_request_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
