# Generated by Django 5.0.1 on 2024-03-02 09:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_match_first_set_remove_match_second_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_number', models.CharField(max_length=20)),
                ('player1_point', models.IntegerField()),
                ('player2_point', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.match')),
            ],
        ),
    ]
