# Generated by Django 5.0.1 on 2024-03-04 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='overall_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='overall_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='forround',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.round'),
        ),
    ]
