# Generated by Django 5.0.1 on 2024-02-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_minuspoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='minuspoint',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
